"""add priority column to todos

Revision ID: f5ad03e57eef
Revises: 5697ed263f56
Create Date: 2026-08-18 20:47:23.371189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ad03e57eef'
down_revision: Union[str, Sequence[str], None] = '5697ed263f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [column['name'] for column in inspector.get_columns('todos')]

    if 'priority' not in columns:
        with op.batch_alter_table('todos') as batch_op:
            batch_op.add_column(
                sa.Column('priority', sa.String(), nullable=False, server_default='medium')
            )
            batch_op.alter_column('priority', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
